---
- set_fact:
    certbot_cert_name: "{{ certbot_host | default(ansible_host) }}"
  when: certbot_cert_name is not defined

- name: Check existing key
  stat: path=/etc/letsencrypt/live/{{ certbot_cert_name }}/privkey.pem
  register: key_file

- name: Ensure www directory exist
  file:
    state: directory
    path: "{{ certbot_www_dir }}"

- name: Ask for a certificate from Lets Encrypt
  shell: "yes | /opt/letsencrypt/certbot-auto certonly {{ certbot_agree_tos }} --webroot -w {{ certbot_www_dir }} --cert-name {{ certbot_cert_name }} -d {{ certbot_host | default(ansible_host) }}{% for extra_host in certbot_extra_hosts|default([]) %} -d {{ extra_host }} {% endfor %} --email {{ certbot_admin_email }}"
  when: key_file.stat.islnk is not defined
